feat: add volume and progress bar for audio
and-gurin/momentum pull request #1
Opened 2023-02-23 14:21 UTC by and-gurin

Do I need to describe what I did?

2023-02-23 15:04 UTC, SergeyKhval requested changes

2023-02-23 15:04 UTC, SergeyKhval commented on src/sass/style.css.map
> -{"version":3,"sourceRoot":"","sources":["base/_abstract.scss","base/_base.scss","vendors/_owf.scss","layouts/_wrapper.scss","layouts/_header.scss","layouts/_footer.scss","components/_main.scss"],"nam
`map` files should not be under version control. you can add it to `.gitignore` file

2023-02-23 15:04 UTC, SergeyKhval commented on src/sass/style.css
> +.icono-areaChart,
your built assets should not be under version control. only the source code should be here. ideally you should have a `build` command that will take your src and prepare the app for deployment. all the output of this build command should not be under version control

2023-02-23 15:04 UTC, SergeyKhval commented on src/js/audio-player.js
> +    if (document.querySelector('.durationTime').innerHTML === "NaN:NaN") {
this problem should be fixed inside `formatTime` function. it should never return `NaN:NaN`. you can do smth like
```js
if (isNaN(min)) min = "0"
if (isNaN(sec)) sec = "00"
```

2023-02-23 15:04 UTC, SergeyKhval commented on src/js/audio-player.js
> +    document.querySelector('.currentTime').innerHTML = (formatTime(Math.floor(audio.currentTime)));
also the problem with your `NaN` values is coming from here. I suppose at some point your `audio.currentTime` is `undefined` resulting in `undefined / 60` returning `NaN`. the easy way to fix this is to wrap everything in `if(audio.currentTime)`. the better solution is to figure out why it becomes `undefined`

2023-02-23 15:04 UTC, SergeyKhval commented on src/js/audio-player.js
> +    progressBar.max = audio.duration;
do you need to set `progressBar.max` every 50 milisesconds? it looks like you only need to do it once when the new song starts

2023-02-23 15:04 UTC, SergeyKhval commented on src/js/audio-player.js
> +    audio.currentTime = progressBar.value;
I think it's better to get the value of your progressbar inside an event listener. 

```js
progressBar.addEventListener('change', function(event){
  audio.currentTime = event.target.value
});
```

What you're doing here is called side effects (and you also do it in other places, but this one is easy to improve). Basically it means that you're operating on the values outside of function scope. Generally the code is easier to work with when it has as few side effects as possible. compare this 2 functions:

```js
function sum(a, b){ return a + b}

function log(){
  console.log(document.querySelector('.some-class'))
}
```
the first one is called `pure` function, because it does not produce side effects and only operates on the values it receives as params. the second one has a side effect of logging the value in console an also querying the document for an element. the first one is generally easier to work with and debug

2023-02-23 15:04 UTC, SergeyKhval commented on src/js/audio-player.js
> +  document.querySelector(".volume-percentage").style.width = newVolume * 100 + '%';
you store references to some elements in the outer scope and some elements you query inside your event handlers. what's the point? I suggest you extract all of your elements into the parent scope (unless they're dynamically created) and just use them as needed. fix here and in other event handlers

2023-02-23 15:04 UTC, SergeyKhval commented on src/js/audio-player.js
> +    volumeEl.classList.remove("icono-volumeMedium");
if you're using a string multiple times then create a variably for it

2023-02-23 15:04 UTC, SergeyKhval commented on src/sass/layouts/_header.scss
> +        .volume-percentage {
do not use nested selectors. just create specific and unique classes. I see that you're trying to use BEM, so just create proper classes for your elements and remove nesting as much as possible

2023-02-23 15:04 UTC, SergeyKhval commented on src/sass/layouts/_header.scss
> +input[type=range]::-webkit-slider-runnable-track {
you're using SCSS, here is a trick

```scss
input[type=range]{
  &::-webkit-slider-runnable-track {}

  &::-webkit-slider-thumb {}

  &::-moz-range-track{}

  &::-moz-range-thumb {}
}
```

2023-02-23 15:04 UTC, SergeyKhval commented on src/sass/layouts/_header.scss
> +.audio-player-controls__wrapper {
SCSS plays well with BEM

```scss
.audio-play-controls {
  /* audio player controls styles here*/

  &__wrapper {
    /* wrapper styles here */
  }
}
```

2023-02-23 21:39 UTC, and-gurin commented on src/sass/layouts/_header.scss
> +.audio-player-controls__wrapper {
.audio-player-controls {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    &__wrapper {
        display: flex;
        align-items: center;
        justify-content: space-between;
        width: 120px;
        height: 50px;
        margin-bottom: 8px;
    }
}

2023-02-23 21:40 UTC, and-gurin commented on src/sass/layouts/_header.scss
> +.audio-player-controls__wrapper {
`.audio-player-controls {
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
    &__wrapper {
        display: flex;
        align-items: center;
        justify-content: space-between;
        width: 120px;
        height: 50px;
        margin-bottom: 8px;
    }
}`

2023-02-24 14:52 UTC, SergeyKhval requested changes

2023-02-24 14:52 UTC, SergeyKhval commented on src/js/audio-player-progress.js
> +const volumeEl = document.querySelector(".volume-container .volume");
do you need nested selector here? can it be just `".volume"`?

2023-02-24 14:52 UTC, SergeyKhval commented on index.html
> +    <script type="module" src="./dist/main.js"></script>
shouldn't webpack take care of this?

2023-02-24 14:52 UTC, SergeyKhval commented on package.json
> +    "style": "sass --watch src/sass/style.scss src/sass/style.css",
this also should probably be handled by webpack

2023-02-24 14:52 UTC, SergeyKhval commented on src/js/audio-player-progress.js
> +const currentTime = document.querySelector('.currentTime');
why do you use double quotes around some strings and single quotes around the others? please be consistent and follow one code style. fix everywhere

2023-02-24 14:52 UTC, SergeyKhval commented on src/js/audio-player-progress.js
> +    if (sec < 10){
what will happen if `sec === "00"` (from previous line) at this point?
a better approach will be to use `padStart` method:

```js
return `${min}:${sec.padStart(2, '0')`
```

and remove this `if` check

2023-02-24 14:52 UTC, SergeyKhval commented on src/sass/style.css
> -.audio-player__controls {
this file is still not removed from version control

2023-02-24 14:52 UTC, SergeyKhval commented on src/sass/style.css.map
> +{"version":3,"sourceRoot":"","sources":["base/_abstract.scss","base/_base.scss","vendors/_owf.scss","layouts/_wrapper.scss","layouts/_header.scss","layouts/_footer.scss","components/_main.scss"],"nam
this file is still not removed from version control

2023-02-24 14:52 UTC, SergeyKhval commented on webpack.config.js
> +       test: /\.txt/,
do you have txt assets? do you need a rule for it?

2023-02-24 14:52 UTC, SergeyKhval commented on src/js/weather.js
> +    try {
It is good, that you decided to improve this part, but I recommend to keep the scope of the PR consistent and not add new staff until you resolve all the existing things. new staff should go to a separate PR. no need to remove it from here, just for the future

2023-02-24 14:52 UTC, SergeyKhval commented on src/js/weather.js
> +const getCityFromLocalStorage = () => city.value = !localStorage.getItem('city') ? 'Minsk' : localStorage.getItem('city');
generaly it is easier to read affirmative conditions

```js
city.value = localStorage.getItem('city') ? localStorage.getItem('city') : 'Minsk'
```

2023-02-25 07:41 UTC, SergeyKhval approved these changes

2023-02-25 07:53 UTC, merged